# This file is a template, and might need editing before it works on your project.
docker-build-master:
  tags:
    - privileged
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$CI_REGISTRY_IMAGE" || true
    - docker build --pull --cache-from "$CI_REGISTRY_IMAGE" --tag "$CI_REGISTRY_IMAGE:latest" .
    - docker volume create openstreetmap-data
    - docker run --rm -v openstreetmap-data:/var/lib/postgresql/12/main "$CI_REGISTRY_IMAGE:latest" import
    - docker run --rm --name "osm-ts-$CI_COMMIT_SHA" -v openstreetmap-data:/var/lib/postgresql/12/main -p 8080:80 -d "$CI_REGISTRY_IMAGE:latest" run
    - sleep 30
    - docker stop "osm-ts-$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:latest"

  only:
    - master

docker-build:
  tags:
    - privileged
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$CI_REGISTRY_IMAGE" || true
    - docker build --pull --cache-from "$CI_REGISTRY_IMAGE" --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker volume create openstreetmap-data
    - docker run --rm -v openstreetmap-data:/var/lib/postgresql/12/main "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" import
    - docker run --rm --name "osm-ts-$CI_COMMIT_SHA" -v openstreetmap-data:/var/lib/postgresql/12/main -p 8080:80 -d "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" run
    - sleep 30
    - docker stop "osm-ts-$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
